{
 "title": "Dashboard Incidentes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<P>\r\n<P>\r\n<center><img style=\" width=\"80\" height=\"80\" \" src=\"https://loja.learnit.ao/wp-content/uploads/2024/10/Learnit.png\" ></center>\r\n<p>\r\n<center><h5> LEARNIT</h5></center>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(i.itemid) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR\r\norder by Total DESC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(i.itemid) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR\r\norder by Total DESC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(i.itemid) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR AND i.status = 0 AND h.status = 0\r\norder by Total DESC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(i.itemid) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE t.value = 1 AND t.status = 0 AND p.r_clock = 0 AND i.status = 0 AND h.status = 0\r\norder by Total DESC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(i.itemid) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE t.value = 0 AND t.status = 0 AND p.r_clock > 0 AND FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR AND i.status = 0 AND h.status = 0\r\norder by Total DESC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT g.name AS group_name, COALESCE(COUNT(p.objectid), 0) AS problem_count\r\nFROM hstgrp g\r\nLEFT JOIN hosts_groups hg ON (g.groupid = hg.groupid)\r\nLEFT JOIN hosts h ON (hg.hostid = h.hostid)\r\nLEFT JOIN items i ON (h.hostid = i.hostid)\r\nLEFT JOIN (\r\n    SELECT itemid, triggerid, MAX(functionid) AS max_functionid\r\n    FROM functions\r\n    GROUP BY itemid, triggerid\r\n) f ON (i.itemid = f.itemid)\r\nLEFT JOIN triggers t ON (f.triggerid = t.triggerid)\r\nLEFT JOIN problem p ON (t.triggerid = p.objectid AND p.r_clock = 0)\r\nWHERE ((t.value = 1 AND t.status = 0) OR p.objectid IS NULL)\r\nAND g.name in ('Switch','Sites','Zabbix servers','Router','Mikrotik','OLT','Linux','Windows Server') AND i.status = 0 AND h.status = 0\r\nGROUP BY g.name;\r\n"
    }
   ]
  },
  {
   "title": "Tabela de Problemas Ativos (Agora)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\n    SELECT\r\n        DATE_FORMAT(FROM_UNIXTIME(p.clock), '%Y-%m-%d %H:%i:%s') as Horario,\r\n                CASE\r\n            WHEN p.severity = 0 THEN 'Not classified'\r\n            WHEN p.severity = 1 THEN 'Information'\r\n            WHEN p.severity = 2 THEN 'Warning'\r\n            WHEN p.severity = 3 THEN 'Average'\r\n            WHEN p.severity = 4 THEN 'High'\r\n            WHEN p.severity = 5 THEN 'Disaster'\r\n            ELSE 'Unknown'\r\n        END AS Severidade,\r\n        CASE\r\n\t\t\tWHEN p.r_clock = 0 THEN \"00:00:00\"\r\n            ELSE SEC_TO_TIME(TIMESTAMPDIFF(SECOND, FROM_UNIXTIME(p.clock), FROM_UNIXTIME(p.r_clock)))\r\n\t\tEND AS \"Tempo decorrido\",\r\n\t\tCASE\r\n\t\t\tWHEN p.r_clock > 0 THEN \"Resolvido\"\r\n            WHEN p.r_clock = 0 THEN \"Problema\"\r\n\t\tEND AS Status,\r\n        h.host as Host,\r\n        CONCAT(it.ip, it.dns) AS IP,\r\n        i.name Item,\r\n        p.name as Problema,\r\n        CONCAT(\r\n            FLOOR(TIMESTAMPDIFF(DAY, FROM_UNIXTIME(p.clock), NOW())),\r\n            'd ',\r\n            MOD(TIMESTAMPDIFF(HOUR, FROM_UNIXTIME(p.clock), NOW()), 24),\r\n            'h ',\r\n            MOD(TIMESTAMPDIFF(MINUTE, FROM_UNIXTIME(p.clock), NOW()), 60),\r\n            'm '\r\n        ) AS Duracao,\r\n\t\tCONCAT(\r\n\t\t\tIFNULL(CAST(huint_last.value AS CHAR), ''),\r\n\t\t\tIFNULL(CAST(h_last.value AS CHAR), '')\r\n        ) AS \"Last\",\r\n        CONCAT(\r\n            IFNULL(CAST(tr_uint.value_min AS CHAR), ''),\r\n            IFNULL(CAST(tr_avg.value_min AS CHAR), '')\r\n        ) AS \"Min\",\r\n\t\tCONCAT(\r\n            IFNULL(CAST(tr_uint.value_avg AS CHAR), ''),\r\n            IFNULL(CAST(tr_avg.value_avg AS CHAR), '')\r\n        ) AS \"Avg\",\r\n\t\tCONCAT(\r\n            IFNULL(CAST(tr_uint.value_max AS CHAR), ''),\r\n            IFNULL(CAST(tr_avg.value_max AS CHAR), '')\r\n        ) AS \"Max\"\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    LEFT JOIN history_uint huint_last ON (i.itemid = huint_last.itemid AND huint_last.clock = (SELECT MAX(clock) FROM history_uint WHERE itemid = i.itemid))\r\n    LEFT JOIN history h_last ON (i.itemid = h_last.itemid AND h_last.clock = (SELECT MAX(clock) FROM history WHERE itemid = i.itemid))\r\n    LEFT JOIN trends_uint tr_uint ON (i.itemid = tr_uint.itemid AND tr_uint.clock = (SELECT MAX(clock) FROM trends_uint WHERE itemid = i.itemid))\r\n    LEFT JOIN trends tr_avg ON (i.itemid = tr_avg.itemid AND tr_avg.clock = (SELECT MAX(clock) FROM trends WHERE itemid = i.itemid))\r\n    WHERE t.value = 1 AND t.status = 0 AND p.r_clock = 0 AND i.status = 0 AND h.status = 0\r\n) AS Subquery\r\nORDER BY Horario DESC;"
    }
   ]
  },
  {
   "title": "Tabela de Problemas p/ Host e Item (24h)",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT h.name AS Host,i.name AS Item, count(i.itemid) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR AND i.status = 0 AND h.status = 0\r\ngroup by i.name,h.hostid\r\norder by Total DESC;"
    }
   ]
  },
  {
   "title": "Incidentes por Severidade (24h)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CASE\r\n            WHEN p.severity = 0 THEN 'Not classified'\r\n            WHEN p.severity = 1 THEN 'Information'\r\n            WHEN p.severity = 2 THEN 'Warning'\r\n            WHEN p.severity = 3 THEN 'Average'\r\n            WHEN p.severity = 4 THEN 'High'\r\n            WHEN p.severity = 5 THEN 'Disaster'\r\n            ELSE 'Unknown'\r\n        END AS Severidade, count(p.severity) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR AND i.status = 0 AND h.status = 0\r\ngroup by p.severity\r\norder by Total DESC;"
    }
   ]
  },
  {
   "title": "Tabela de Problemas Agregado /p Host (24h)",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT h.name AS Host, count(h.hostid) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR AND i.status = 0 AND h.status = 0\r\ngroup by h.name\r\norder by Total DESC;"
    }
   ]
  },
  {
   "title": "Tabela de Problemas (24h)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\n    SELECT\r\n        DATE_FORMAT(FROM_UNIXTIME(p.clock), '%Y-%m-%d %H:%i:%s') as Horario,\r\n                CASE\r\n            WHEN p.severity = 0 THEN 'Not classified'\r\n            WHEN p.severity = 1 THEN 'Information'\r\n            WHEN p.severity = 2 THEN 'Warning'\r\n            WHEN p.severity = 3 THEN 'Average'\r\n            WHEN p.severity = 4 THEN 'High'\r\n            WHEN p.severity = 5 THEN 'Disaster'\r\n            ELSE 'Unknown'\r\n        END AS Severidade,\r\n        CASE\r\n\t\t\tWHEN p.r_clock = 0 THEN \"00:00:00\"\r\n            ELSE SEC_TO_TIME(TIMESTAMPDIFF(SECOND, FROM_UNIXTIME(p.clock), FROM_UNIXTIME(p.r_clock)))\r\n\t\tEND AS \"Tempo decorrido\",\r\n\t\tCASE\r\n\t\t\tWHEN p.r_clock > 0 THEN \"Resolvido\"\r\n            WHEN p.r_clock = 0 THEN \"Problema\"\r\n\t\tEND AS Status,\r\n        h.host as Host,\r\n        CONCAT(it.ip, it.dns) AS IP,\r\n        i.name Item,\r\n        p.name as Problema,\r\n        CASE\r\n        WHEN p.r_clock = 0 THEN \"0d 0h 0m\"\r\n        ELSE\r\n        CONCAT(\r\n            FLOOR(TIMESTAMPDIFF(DAY, FROM_UNIXTIME(p.clock), FROM_UNIXTIME(p.r_clock))),\r\n            'd ',\r\n            MOD(TIMESTAMPDIFF(HOUR, FROM_UNIXTIME(p.clock), FROM_UNIXTIME(p.r_clock)), 24),\r\n            'h ',\r\n            MOD(TIMESTAMPDIFF(MINUTE, FROM_UNIXTIME(p.clock), FROM_UNIXTIME(p.r_clock)), 60),\r\n            'm '\r\n        ) \r\n        END AS Duracao,\r\n\t\tCONCAT(\r\n\t\t\tIFNULL(CAST(huint_last.value AS CHAR), ''),\r\n\t\t\tIFNULL(CAST(h_last.value AS CHAR), '')\r\n        ) AS \"Last\",\r\n        CONCAT(\r\n            IFNULL(CAST(tr_uint.value_min AS CHAR), ''),\r\n            IFNULL(CAST(tr_avg.value_min AS CHAR), '')\r\n        ) AS \"Min\",\r\n\t\tCONCAT(\r\n            IFNULL(CAST(tr_uint.value_avg AS CHAR), ''),\r\n            IFNULL(CAST(tr_avg.value_avg AS CHAR), '')\r\n        ) AS \"Avg\",\r\n\t\tCONCAT(\r\n            IFNULL(CAST(tr_uint.value_max AS CHAR), ''),\r\n            IFNULL(CAST(tr_avg.value_max AS CHAR), '')\r\n        ) AS \"Max\"\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    LEFT JOIN history_uint huint_last ON (i.itemid = huint_last.itemid AND huint_last.clock = (SELECT MAX(clock) FROM history_uint WHERE itemid = i.itemid))\r\n    LEFT JOIN history h_last ON (i.itemid = h_last.itemid AND h_last.clock = (SELECT MAX(clock) FROM history WHERE itemid = i.itemid))\r\n    LEFT JOIN trends_uint tr_uint ON (i.itemid = tr_uint.itemid AND tr_uint.clock = (SELECT MAX(clock) FROM trends_uint WHERE itemid = i.itemid))\r\n    LEFT JOIN trends tr_avg ON (i.itemid = tr_avg.itemid AND tr_avg.clock = (SELECT MAX(clock) FROM trends WHERE itemid = i.itemid))\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR AND i.status = 0 AND h.status = 0\r\n) AS Subquery\r\nORDER BY Horario DESC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(i.itemid) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR\r\norder by Total DESC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.severity) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR AND p.severity = 1 AND i.status = 0 AND h.status = 0\r\norder by Total DESC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.severity) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR AND p.severity = 2 AND i.status = 0 AND h.status = 0\r\norder by Total DESC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.severity) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR AND p.severity = 3 AND i.status = 0 AND h.status = 0\r\norder by Total DESC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.severity) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR AND p.severity = 4 AND i.status = 0 AND h.status = 0\r\norder by Total DESC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.severity) AS Total\r\n    FROM problem p\r\n    INNER JOIN (\r\n        SELECT max(itemid) AS itemid, max(triggerid) AS triggerid\r\n        FROM functions\r\n        GROUP BY triggerid\r\n    ) f ON p.objectid = f.triggerid\r\n    INNER JOIN items i ON (f.itemid = i.itemid)\r\n    INNER JOIN hosts h ON (i.hostid = h.hostid)\r\n    LEFT JOIN interface it ON (it.interfaceid = i.interfaceid)\r\n    INNER JOIN triggers t ON (f.triggerid = t.triggerid)\r\n    WHERE FROM_UNIXTIME(p.clock) >= NOW() - INTERVAL 24 HOUR AND p.severity = 5 AND i.status = 0 AND h.status = 0\r\norder by Total DESC;"
    }
   ]
  }
 ]
}